name: auto_garage
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  formz: ^0.6.0
  formz_input:
    path: packages/formz_input
  fpdart: ^1.0.0
  internet_connection_checker_plus: ^2.0.0
  internet_connection_check_service:
    path: packages/internet_connection_check_service
  intl: ^0.18.1
  
  image_picker: ^1.0.1
  
  go_router: ^10.0.0
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  local_auth: ^2.1.6
  wtf_sliding_sheet: ^1.1.1

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.0
  path_provider: ^2.0.15
  very_good_analysis: ^5.0.0+1
  melos: ^3.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
