name: crashlytics_service
description: Dart package which manages the collection of crash reports in the app.

environment: 
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.5

dependencies:
  firebase_crashlytics: ^3.0.9

dev_dependencies:
  mockito: ^5.0.15
  test: ^1.20.1
  very_good_analysis: ^3.0.0