// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc4ksYOO-AeFf6eibciJsfnY8lNlsbO8E',
    appId: '1:457388116738:web:64801325e217daaf1b101b',
    messagingSenderId: '457388116738',
    projectId: 'kriss-auto-garage',
    authDomain: 'kriss-auto-garage.firebaseapp.com',
    storageBucket: 'kriss-auto-garage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLHfshOhzY7a46uIlK7WDf5WUUrDabVAU',
    appId: '1:457388116738:android:849d1d9fe7b03d8c1b101b',
    messagingSenderId: '457388116738',
    projectId: 'kriss-auto-garage',
    storageBucket: 'kriss-auto-garage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9KrAN21AR1b5IJnvMo9l7tjVEw6panEA',
    appId: '1:457388116738:ios:61e2fdf56977b2e91b101b',
    messagingSenderId: '457388116738',
    projectId: 'kriss-auto-garage',
    storageBucket: 'kriss-auto-garage.appspot.com',
    iosClientId: '457388116738-jpjoo7k67hcpd5l9d2udmq6c82jcp07d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gordonAutoGarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9KrAN21AR1b5IJnvMo9l7tjVEw6panEA',
    appId: '1:457388116738:ios:5fb1fb5b75e7ddab1b101b',
    messagingSenderId: '457388116738',
    projectId: 'kriss-auto-garage',
    storageBucket: 'kriss-auto-garage.appspot.com',
    iosClientId: '457388116738-o0ueri62mi75ju1s8qls54g5asdnmu44.apps.googleusercontent.com',
    iosBundleId: 'com.example.gordonAutoGarage.RunnerTests',
  );
}
